//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heka.DataAccess.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Dye
    {
        
        public Dye()
        {
            this.MoldTest = new HashSet<MoldTest>();
            this.WorkOrderDetail = new HashSet<WorkOrderDetail>();
        }
    
        public int Id { get; set; }
        public string DyeCode { get; set; }
        public string DyeName { get; set; }
        public string RalCode { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUserId { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedUserId { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        [InverseProperty("Dye")]
        public virtual ICollection<MoldTest> MoldTest { get; set; }

        [InverseProperty("Dye")]
        public virtual ICollection<WorkOrderDetail> WorkOrderDetail { get; set; }
    }
}
