//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heka.DataAccess.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class EntryQualityDataDetail
    {
        public int Id { get; set; }

        [ForeignKey("EntryQualityData")]
        public Nullable<int> EntryQualityDataId { get; set; }

        [ForeignKey("EntryQualityPlanDetail")]
        public Nullable<int> EntryQualityPlanDetailId { get; set; }
        public Nullable<int> OrderNo { get; set; }
        public string FaultExplanation { get; set; }
        public Nullable<decimal> SampleQuantity { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUserId { get; set; }
        public Nullable<bool> CheckResult { get; set; }
        public Nullable<decimal> NumericResult { get; set; }
        public Nullable<bool> IsOk { get; set; }

        public virtual EntryQualityData EntryQualityData { get; set; }
        public virtual EntryQualityPlanDetail EntryQualityPlanDetail { get; set; }
    }
}
