//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heka.DataAccess.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class EntryQualityPlan
    {
        
        public EntryQualityPlan()
        {
            this.EntryQualityData = new HashSet<EntryQualityData>();
            this.EntryQualityPlanDetail = new HashSet<EntryQualityPlanDetail>();
        }
    
        public int Id { get; set; }
        public string QualityControlCode { get; set; }
        public Nullable<int> OrderNo { get; set; }

        [ForeignKey("ItemGroup")]
        public Nullable<int> ItemGroupId { get; set; }

        [ForeignKey("ItemCategory")]
        public Nullable<int> ItemCategoryId { get; set; }
        public string ItemGroupText { get; set; }
        public string PeriodType { get; set; }
        public string AcceptanceCriteria { get; set; }
        public string ControlDevice { get; set; }
        public string Method { get; set; }
        public string Responsible { get; set; }
        public string RecordType { get; set; }
    
        
        public virtual ICollection<EntryQualityData> EntryQualityData { get; set; }
        public virtual ItemCategory ItemCategory { get; set; }
        public virtual ItemGroup ItemGroup { get; set; }
        
        [InverseProperty("EntryQualityPlan")]
        public virtual ICollection<EntryQualityPlanDetail> EntryQualityPlanDetail { get; set; }
    }
}
