//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heka.DataAccess.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Equipment
    {
        public int Id { get; set; }
        public string EquipmentCode { get; set; }
        public string EquipmentName { get; set; }

        [ForeignKey("Plant")]
        public Nullable<int> PlantId { get; set; }

        [ForeignKey("Machine")]
        public Nullable<int> MachineId { get; set; }
        public string Manufacturer { get; set; }
        public string ModelNo { get; set; }
        public string SerialNo { get; set; }
        public string Location { get; set; }

        [ForeignKey("User")]
        public Nullable<int> ResponsibleUserId { get; set; }
        public Nullable<bool> IsCritical { get; set; }

        [ForeignKey("EquipmentCategory")]
        public Nullable<int> EquipmentCategoryId { get; set; }
    
        public virtual EquipmentCategory EquipmentCategory { get; set; }
        public virtual Plant Plant { get; set; }
        public virtual User User { get; set; }
        public virtual Machine Machine { get; set; }
    }
}
