//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heka.DataAccess.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class EquipmentCategory
    {
        
        public EquipmentCategory()
        {
            this.Equipment = new HashSet<Equipment>();
        }
    
        public int Id { get; set; }
        public string EquipmentCategoryCode { get; set; }
        public string EquipmentCategoryName { get; set; }

        [ForeignKey("Plant")]
        public Nullable<int> PlantId { get; set; }
        public Nullable<bool> IsCritical { get; set; }
    
        
        [InverseProperty("EquipmentCategory")]
        public virtual ICollection<Equipment> Equipment { get; set; }
        public virtual Plant Plant { get; set; }
    }
}
