//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heka.DataAccess.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class IncidentCategory
    {
        
        public IncidentCategory()
        {
            this.Incident = new HashSet<Incident>();
        }
    
        public int Id { get; set; }
        public string IncidentCategoryCode { get; set; }
        public string IncidentCategoryName { get; set; }

        [InverseProperty("IncidentCategory")]
        public virtual ICollection<Incident> Incident { get; set; }
    }
}
