//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heka.DataAccess.Context
{
    using Heka.DataAccess.Context.Models;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Invoice
    {
        
        public Invoice()
        {
            this.ItemReceipt = new HashSet<ItemReceipt>();
            this.ItemLoad = new HashSet<ItemLoad>();

        }

        public int Id { get; set; }
        public Nullable<int> InvoiceType { get; set; }
        public string InvoiceNo { get; set; }
        public Nullable<int> InvoiceStatus { get; set; }
        public string DocumentNo { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }

        [ForeignKey("Firm")]
        public Nullable<int> FirmId { get; set; }

        [ForeignKey("Plant")]
        public Nullable<int> PlantId { get; set; }
        public string Explanation { get; set; }
        public Nullable<decimal> SubTotal { get; set; }
        public Nullable<decimal> DiscountTotal { get; set; }
        public Nullable<decimal> TaxTotal { get; set; }
        public Nullable<decimal> GrandTotal { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUserId { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedUserId { get; set; }
    
        public virtual Firm Firm { get; set; }
        public virtual Plant Plant { get; set; }

        [InverseProperty("Invoice")]
        public virtual ICollection<ItemReceipt> ItemReceipt { get; set; }

        [InverseProperty("Invoice")]
        public virtual ICollection<ItemLoad> ItemLoad { get; set; }
    }
}
