//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heka.DataAccess.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ItemWarehouse
    {
        public int Id { get; set; }

        [ForeignKey("Item")]
        public Nullable<int> ItemId { get; set; }

        [ForeignKey("Warehouse")]
        public Nullable<int> WarehouseId { get; set; }
        public Nullable<bool> IsAllowed { get; set; }
        public Nullable<decimal> MinimumQuantity { get; set; }
        public Nullable<decimal> MaximumQuantity { get; set; }
        public Nullable<int> MinimumBehaviour { get; set; }
        public Nullable<int> MaximumBehaviour { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
