//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heka.DataAccess.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ItemOrderItemNeeds
    {
        public int Id { get; set; }

        [ForeignKey("ItemOrderDetail")]
        public Nullable<int> ItemOrderDetailId { get; set; }

        [ForeignKey("ItemOrder")]
        public Nullable<int> ItemOrderId { get; set; }

        [ForeignKey("Item")]
        public Nullable<int> ItemId { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> RemainingNeedsQuantity { get; set; }
        public Nullable<System.DateTime> CalculatedDate { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual ItemOrder ItemOrder { get; set; }
        public virtual ItemOrderDetail ItemOrderDetail { get; set; }
    }
}
