//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heka.DataAccess.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ItemReceiptConsume
    {
        public int Id { get; set; }

        [ForeignKey("ItemReceiptDetailConsumed")]
        public Nullable<int> ConsumedReceiptDetailId { get; set; }

        [ForeignKey("ItemReceiptDetailConsumer")]
        public Nullable<int> ConsumerReceiptDetailId { get; set; }
        public Nullable<decimal> UsedQuantity { get; set; }
        public Nullable<decimal> UsedGrossQuantity { get; set; }

        [ForeignKey("UnitType")]
        public Nullable<int> UnitId { get; set; }
    
        public virtual ItemReceiptDetail ItemReceiptDetailConsumed { get; set; }
        public virtual ItemReceiptDetail ItemReceiptDetailConsumer { get; set; }
        public virtual UnitType UnitType { get; set; }
    }
}
