//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heka.DataAccess.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ItemCategory
    {
        
        public ItemCategory()
        {
            this.EntryQualityPlan = new HashSet<EntryQualityPlan>();
            this.Item = new HashSet<Item>();
            this.ItemGroup = new HashSet<ItemGroup>();
        }
    
        public int Id { get; set; }
        public string ItemCategoryCode { get; set; }
        public string ItemCategoryName { get; set; }

        [ForeignKey("Plant")]
        public Nullable<int> PlantId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUserId { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedUserId { get; set; }


        [InverseProperty("ItemCategory")]
        public virtual ICollection<EntryQualityPlan> EntryQualityPlan { get; set; }

        [InverseProperty("ItemCategory")]
        public virtual ICollection<Item> Item { get; set; }
        public virtual Plant Plant { get; set; }

        [InverseProperty("ItemCategory")]
        public virtual ICollection<ItemGroup> ItemGroup { get; set; }
    }
}
