//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heka.DataAccess.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ItemSerial
    {
        public int Id { get; set; }

        [ForeignKey("Item")]
        public Nullable<int> ItemId { get; set; }

        [ForeignKey("ItemReceiptDetail")]
        public Nullable<int> ItemReceiptDetailId { get; set; }
        public string SerialNo { get; set; }
        public Nullable<int> ReceiptType { get; set; }
        public Nullable<int> SerialStatus { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUserId { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedUserId { get; set; }
        public Nullable<decimal> FirstQuantity { get; set; }
        public Nullable<decimal> LiveQuantity { get; set; }

        [ForeignKey("WorkOrderDetail")]
        public Nullable<int> WorkOrderDetailId { get; set; }
        public Nullable<int> SerialType { get; set; }
        public Nullable<int> InPackageQuantity { get; set; }
        public Nullable<DateTime> ShiftBelongsToDate { get; set; }

        public virtual Item Item { get; set; }
        public virtual ItemReceiptDetail ItemReceiptDetail { get; set; }
        public virtual WorkOrderDetail WorkOrderDetail { get; set; }
    }
}
