//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heka.DataAccess.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ItemGroup
    {
        
        public ItemGroup()
        {
            this.EntryQualityPlan = new HashSet<EntryQualityPlan>();
            this.Item = new HashSet<Item>();
            this.ItemVariant = new HashSet<ItemVariant>();

        }

        public int Id { get; set; }
        public string ItemGroupCode { get; set; }
        public string ItemGroupName { get; set; }

        [ForeignKey("ItemCategory")]
        public Nullable<int> ItemCategoryId { get; set; }

        [ForeignKey("Plant")]
        public Nullable<int> PlantId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUserId { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedUserId { get; set; }

        [InverseProperty("ItemGroup")]
        public virtual ICollection<EntryQualityPlan> EntryQualityPlan { get; set; }

        [InverseProperty("ItemGroup")]
        public virtual ICollection<ItemVariant> ItemVariant { get; set; }

        [InverseProperty("ItemGroup")]
        public virtual ICollection<Item> Item { get; set; }
        public virtual ItemCategory ItemCategory { get; set; }
        public virtual Plant Plant { get; set; }
    }
}
