//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heka.DataAccess.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ItemRequestDetail
    {
        
        public ItemRequestDetail()
        {
            this.ItemOrderDetail = new HashSet<ItemOrderDetail>();
        }
    
        public int Id { get; set; }

        [ForeignKey("ItemRequest")]
        public Nullable<int> ItemRequestId { get; set; }
        public Nullable<int> LineNumber { get; set; }

        [ForeignKey("Item")]
        public Nullable<int> ItemId { get; set; }

        [ForeignKey("UnitType")]
        public Nullable<int> UnitId { get; set; }
        public Nullable<decimal> Quantity { get; set; }
        public Nullable<decimal> NetQuantity { get; set; }
        public Nullable<decimal> ApprovedQuantity { get; set; }
        public string Explanation { get; set; }
        public Nullable<int> RequestStatus { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUserId { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedUserId { get; set; }
    
        public virtual Item Item { get; set; }

        [InverseProperty("ItemRequestDetail")]
        public virtual ICollection<ItemOrderDetail> ItemOrderDetail { get; set; }
        public virtual ItemRequest ItemRequest { get; set; }
        public virtual UnitType UnitType { get; set; }
    }
}
