//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heka.DataAccess.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class LayoutItem
    {
        public int Id { get; set; }

        [ForeignKey("Machine")]
        public Nullable<int> MachineId { get; set; }
        public string PositionData { get; set; }
        public string RotationData { get; set; }
        public string ScalingData { get; set; }
        public string Title { get; set; }

        [ForeignKey("Plant")]
        public Nullable<int> PlantId { get; set; }
    
        public virtual Plant Plant { get; set; }
        public virtual Machine Machine { get; set; }
    }
}
