//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heka.DataAccess.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class MachineMaintenanceInstruction
    {
        
        public MachineMaintenanceInstruction()
        {
            this.MachineMaintenanceInstructionEntry = new HashSet<MachineMaintenanceInstructionEntry>();
        }
    
        public int Id { get; set; }

        [ForeignKey("Machine")]
        public Nullable<int> MachineId { get; set; }
        public string UnitName { get; set; }
        public string PeriodType { get; set; }
        public string ToDoList { get; set; }
        public string Responsible { get; set; }
        public Nullable<int> LineNumber { get; set; }
    
        
        [InverseProperty("MachineMaintenanceInstruction")]
        public virtual ICollection<MachineMaintenanceInstructionEntry> MachineMaintenanceInstructionEntry { get; set; }
        public virtual Machine Machine { get; set; }
    }
}
