//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heka.DataAccess.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class PrinterQueue
    {
        public int Id { get; set; }

        [ForeignKey("SystemPrinter")]
        public Nullable<int> PrinterId { get; set; }
        public Nullable<int> RecordType { get; set; }
        public Nullable<int> RecordId { get; set; }
        public Nullable<int> OrderNo { get; set; }
        public string AllocatedPrintData { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual SystemPrinter SystemPrinter { get; set; }
    }
}
