//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heka.DataAccess.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Process
    {
        
        public Process()
        {
            this.ActualRouteHistory = new HashSet<ActualRouteHistory>();
            this.RouteItem = new HashSet<RouteItem>();
        }
    
        public int Id { get; set; }
        public string ProcessCode { get; set; }
        public string ProcessName { get; set; }

        [ForeignKey("Plant")]
        public Nullable<int> PlantId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<decimal> TheoreticalDuration { get; set; }

        [ForeignKey("ProcessGroup")]
        public Nullable<int> ProcessGroupId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUserId { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedUserId { get; set; }

        [InverseProperty("Process")]
        public virtual ICollection<ActualRouteHistory> ActualRouteHistory { get; set; }
        public virtual Plant Plant { get; set; }
        public virtual ProcessGroup ProcessGroup { get; set; }

        [InverseProperty("Process")]
        public virtual ICollection<RouteItem> RouteItem { get; set; }
    }
}
