//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heka.DataAccess.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ProcessGroup
    {
        
        public ProcessGroup()
        {
            this.ActualRouteHistory = new HashSet<ActualRouteHistory>();
            this.Process = new HashSet<Process>();
            this.RouteItem = new HashSet<RouteItem>();
        }
    
        public int Id { get; set; }
        public string ProcessGroupCode { get; set; }
        public string ProcessGroupName { get; set; }

        [ForeignKey("Plant")]
        public Nullable<int> PlantId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUserId { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedUserId { get; set; }

        [InverseProperty("ProcessGroup")]
        public virtual ICollection<ActualRouteHistory> ActualRouteHistory { get; set; }
        public virtual Plant Plant { get; set; }

        [InverseProperty("ProcessGroup")]
        public virtual ICollection<Process> Process { get; set; }

        [InverseProperty("ProcessGroup")]
        public virtual ICollection<RouteItem> RouteItem { get; set; }
    }
}
