//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heka.DataAccess.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ProductQualityData
    {
        
        public ProductQualityData()
        {
            this.ProductQualityDataDetail = new HashSet<ProductQualityDataDetail>();
        }
    
        public int Id { get; set; }

        [ForeignKey("Machine")]
        public Nullable<int> MachineId { get; set; }

        [ForeignKey("Item")]
        public Nullable<int> ProductId { get; set; }
        public Nullable<System.DateTime> ControlDate { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUserId { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedUserId { get; set; }
        public string Explanation { get; set; }
    
        public virtual Item Item { get; set; }

        [InverseProperty("ProductQualityData")]
        public virtual ICollection<ProductQualityDataDetail> ProductQualityDataDetail { get; set; }
        public virtual Machine Machine { get; set; }
    }
}
