//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heka.DataAccess.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ProductRecipeDetail
    {
        public int Id { get; set; }

        [ForeignKey("ProductRecipe")]
        public Nullable<int> ProductRecipeId { get; set; }

        [ForeignKey("Item")]
        public Nullable<int> ItemId { get; set; }
        public Nullable<int> ProcessType { get; set; }

        [ForeignKey("UnitType")]
        public Nullable<int> UnitId { get; set; }
        public Nullable<decimal> Quantity { get; set; }

        [ForeignKey("Warehouse")]
        public Nullable<int> WarehouseId { get; set; }
        public Nullable<decimal> WastagePercentage { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUserId { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedUserId { get; set; }
    
        public virtual Item Item { get; set; }
        public virtual ProductRecipe ProductRecipe { get; set; }
        public virtual UnitType UnitType { get; set; }
        public virtual Warehouse Warehouse { get; set; }
    }
}
