//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heka.DataAccess.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ProductRecipe
    {
        
        public ProductRecipe()
        {
            this.ProductRecipeDetail = new HashSet<ProductRecipeDetail>();
        }
    
        public int Id { get; set; }
        public string ProductRecipeCode { get; set; }
        public string Description { get; set; }
        public Nullable<int> ProductRecipeType { get; set; }

        [ForeignKey("Item")]
        public Nullable<int> ProductId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUserId { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedUserId { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual Item Item { get; set; }
        
        [InverseProperty("ProductRecipe")]
        public virtual ICollection<ProductRecipeDetail> ProductRecipeDetail { get; set; }
    }
}
