//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heka.DataAccess.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportTemplate
    {
        public int Id { get; set; }
        public Nullable<int> ReportType { get; set; }
        public string ReportCode { get; set; }
        public string ReportName { get; set; }
        public string FileName { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
