//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heka.DataAccess.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Route
    {
        
        public Route()
        {
            this.RouteItem = new HashSet<RouteItem>();
        }
    
        public int Id { get; set; }
        public string RouteCode { get; set; }
        public string RouteName { get; set; }

        [ForeignKey("Plant")]
        public Nullable<int> PlantId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUserId { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedUserId { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        [ForeignKey("ForexType")]
        public Nullable<int> ForexId { get; set; }

        public virtual Plant Plant { get; set; }
        public virtual ForexType ForexType { get; set; }

        [InverseProperty("Route")]
        public virtual ICollection<RouteItem> RouteItem { get; set; }
    }
}
