//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heka.DataAccess.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Shift
    {
        
        public Shift()
        {
            this.Incident = new HashSet<Incident>();
            this.MachineSignal = new HashSet<MachineSignal>();
            this.ProductionPosture = new HashSet<ProductionPosture>();
            this.ShiftTarget = new HashSet<ShiftTarget>();
            this.WorkOrderSerial = new HashSet<WorkOrderSerial>();
            this.ProductWastage = new HashSet<ProductWastage>();
        }
    
        public int Id { get; set; }
        public string ShiftCode { get; set; }
        public string ShiftName { get; set; }
        public Nullable<System.TimeSpan> StartTime { get; set; }
        public Nullable<System.TimeSpan> EndTime { get; set; }
        public Nullable<bool> IsActive { get; set; }

        [ForeignKey("User")]
        public Nullable<int> ShiftChiefId { get; set; }
    
        [InverseProperty("Shift")]
        public virtual ICollection<Incident> Incident { get; set; }

        [InverseProperty("Shift")]
        public virtual ICollection<MachineSignal> MachineSignal { get; set; }

        [InverseProperty("Shift")]
        public virtual ICollection<ProductionPosture> ProductionPosture { get; set; }
        public virtual User User { get; set; }

        [InverseProperty("Shift")]
        public virtual ICollection<ShiftTarget> ShiftTarget { get; set; }

        [InverseProperty("Shift")]
        public virtual ICollection<WorkOrderSerial> WorkOrderSerial { get; set; }

        [InverseProperty("Shift")]
        public virtual ICollection<ProductWastage> ProductWastage { get; set; }
    }
}
