//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heka.DataAccess.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class ShiftTarget
    {
        public int Id { get; set; }

        [ForeignKey("Shift")]
        public Nullable<int> ShiftId { get; set; }
        public Nullable<System.DateTime> TargetDate { get; set; }
        public Nullable<int> TargetCount { get; set; }

        [ForeignKey("Machine")]
        public Nullable<int> MachineId { get; set; }
    
        public virtual Shift Shift { get; set; }
        public virtual Machine Machine { get; set; }
    }
}
