//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heka.DataAccess.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class SystemPrinter
    {
        
        public SystemPrinter()
        {
            this.PrinterQueue = new HashSet<PrinterQueue>();
        }
    
        public int Id { get; set; }
        public string PrinterCode { get; set; }
        public string PrinterName { get; set; }
        public string AccessPath { get; set; }

        
        public Nullable<int> PlantId { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<decimal> PageWidth { get; set; }
        public Nullable<decimal> PageHeight { get; set; }

        [InverseProperty("SystemPrinter")]
        public virtual ICollection<PrinterQueue> PrinterQueue { get; set; }
    }
}
