//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heka.DataAccess.Context
{
    using Heka.DataAccess.Context.Models;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class UnitType
    {
        
        public UnitType()
        {
            this.ItemOrderDetail = new HashSet<ItemOrderDetail>();
            this.ItemReceiptConsume = new HashSet<ItemReceiptConsume>();
            this.ItemReceiptDetail = new HashSet<ItemReceiptDetail>();
            this.ItemRequestDetail = new HashSet<ItemRequestDetail>();
            this.ItemUnit = new HashSet<ItemUnit>();
            this.ProductRecipeDetail = new HashSet<ProductRecipeDetail>();
            this.ItemOrderConsume = new HashSet<ItemOrderConsume>();
            this.Cost = new HashSet<Cost>();

        }

        public int Id { get; set; }
        public string UnitCode { get; set; }
        public string UnitName { get; set; }

        [ForeignKey("Plant")]
        public Nullable<int> PlantId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUserId { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedUserId { get; set; }

        [InverseProperty("UnitType")]
        public virtual ICollection<ItemOrderDetail> ItemOrderDetail { get; set; }

        [InverseProperty("UnitType")]
        public virtual ICollection<ItemReceiptConsume> ItemReceiptConsume { get; set; }

        [InverseProperty("UnitType")]
        public virtual ICollection<ItemReceiptDetail> ItemReceiptDetail { get; set; }

        [InverseProperty("UnitType")]
        public virtual ICollection<ItemRequestDetail> ItemRequestDetail { get; set; }

        [InverseProperty("UnitType")]
        public virtual ICollection<ItemUnit> ItemUnit { get; set; }
        public virtual Plant Plant { get; set; }

        [InverseProperty("UnitType")]
        public virtual ICollection<ProductRecipeDetail> ProductRecipeDetail { get; set; }

        [InverseProperty("UnitType")]
        public virtual ICollection<ItemOrderConsume> ItemOrderConsume { get; set; }

        [InverseProperty("UnitType")]
        public virtual ICollection<Cost> Cost { get; set; }
    }
}
