//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heka.DataAccess.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class UserAuthType
    {
        
        public UserAuthType()
        {
            this.UserAuth = new HashSet<UserAuth>();
        }
    
        [Key]
        public int Id { get; set; }
        public string AuthTypeCode { get; set; }
        public string AuthTypeName { get; set; }

        [InverseProperty("UserAuthType")]
        public virtual ICollection<UserAuth> UserAuth { get; set; }
    }
}
