//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heka.DataAccess.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class UserRoleSubscription
    {
        public int Id { get; set; }

        [ForeignKey("UserRole")]
        public Nullable<int> UserRoleId { get; set; }
        public Nullable<int> SubscriptionCategory { get; set; }
    
        public virtual UserRole UserRole { get; set; }
    }
}
