//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heka.DataAccess.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Warehouse
    {
        
        public Warehouse()
        {
            //this.ItemLiveStatus = new HashSet<ItemLiveStatus>();
            //this.ItemOrder = new HashSet<ItemOrder>();
            //this.ItemOrder1 = new HashSet<ItemOrder>();
            //this.ItemReceipt = new HashSet<ItemReceipt>();
            //this.ItemReceipt1 = new HashSet<ItemReceipt>();
            //this.ItemWarehouse = new HashSet<ItemWarehouse>();
            //this.ProductRecipeDetail = new HashSet<ProductRecipeDetail>();
            //this.WorkOrderSerial = new HashSet<WorkOrderSerial>();
        }
    
        public int Id { get; set; }
        public string WarehouseCode { get; set; }
        public string WarehouseName { get; set; }
        public Nullable<int> WarehouseType { get; set; }

        [ForeignKey("Plant")]
        public Nullable<int> PlantId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUserId { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedUserId { get; set; }


        //public virtual ICollection<ItemLiveStatus> ItemLiveStatus { get; set; }

        //public virtual ICollection<ItemOrder> ItemOrder { get; set; }

        //public virtual ICollection<ItemOrder> ItemOrder1 { get; set; }

        //public virtual ICollection<ItemReceipt> ItemReceipt { get; set; }

        //public virtual ICollection<ItemReceipt> ItemReceipt1 { get; set; }

        //public virtual ICollection<ItemWarehouse> ItemWarehouse { get; set; }
        public virtual Plant Plant { get; set; }

        //public virtual ICollection<ProductRecipeDetail> ProductRecipeDetail { get; set; }

        //public virtual ICollection<WorkOrderSerial> WorkOrderSerial { get; set; }
    }
}
