//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heka.DataAccess.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class WorkOrderControlType
    {
        
        public WorkOrderControlType()
        {
            this.WorkOrderControl = new HashSet<WorkOrderControl>();
        }
    
        public int Id { get; set; }
        public string ControlCode { get; set; }
        public string ControlName { get; set; }
        public Nullable<int> OrderNo { get; set; }
        public Nullable<bool> IsActive { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUserId { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedUserId { get; set; }


        [InverseProperty("WorkOrderControlType")]
        public virtual ICollection<WorkOrderControl> WorkOrderControl { get; set; }
    }
}
