//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heka.DataAccess.Context
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class WorkOrderCategory
    {
        
        public WorkOrderCategory()
        {
            this.WorkOrder = new HashSet<WorkOrder>();
        }
    
        public int Id { get; set; }
        public string WorkOrderCategoryCode { get; set; }
        public string WorkOrderCategoryName { get; set; }

        [InverseProperty("WorkOrderCategory")]
        public virtual ICollection<WorkOrder> WorkOrder { get; set; }
    }
}
