// <auto-generated />
namespace Heka.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class SerialFaultTypeAdded2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SerialFaultTypeAdded2));
        
        string IMigrationMetadata.Id
        {
            get { return "202201031402567_SerialFaultTypeAdded2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
