// <auto-generated />
namespace Heka.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class VoyageCostUpdateCreatedIdAndUpdateUserIdAdd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(VoyageCostUpdateCreatedIdAndUpdateUserIdAdd));
        
        string IMigrationMetadata.Id
        {
            get { return "202203170854022_VoyageCostUpdate(CreatedIdAndUpdateUserIdAdd)"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
