// <auto-generated />
namespace Heka.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class VehicleCareUpdateGenel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(VehicleCareUpdateGenel));
        
        string IMigrationMetadata.Id
        {
            get { return "202201121825187_VehicleCareUpdate-Genel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
