// <auto-generated />
namespace Heka.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class EntryQualityDetail_TextResult : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EntryQualityDetail_TextResult));
        
        string IMigrationMetadata.Id
        {
            get { return "202206271218243_EntryQualityDetail_TextResult"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
