// <auto-generated />
namespace Heka.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ItemLoadUpdateLoadAuthorAdd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ItemLoadUpdateLoadAuthorAdd));
        
        string IMigrationMetadata.Id
        {
            get { return "202201280157087_ItemLoadUpdate(LoadAuthorAdd)"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
