// <auto-generated />
namespace Heka.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ItemReceiptUpdateOverallQuantity : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ItemReceiptUpdateOverallQuantity));
        
        string IMigrationMetadata.Id
        {
            get { return "202204020611066_ItemReceiptUpdate(OverallQuantity)"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
