// <auto-generated />
namespace Heka.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ItemLoad_Voyage_Relation : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ItemLoad_Voyage_Relation));
        
        string IMigrationMetadata.Id
        {
            get { return "202205131844505_ItemLoad_Voyage_Relation"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
