// <auto-generated />
namespace Heka.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class DriverAccountDetailUpdateUnitTypeIdAdd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DriverAccountDetailUpdateUnitTypeIdAdd));
        
        string IMigrationMetadata.Id
        {
            get { return "202203191201457_DriverAccountDetailUpdate(UnitTypeIdAdd)"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
