//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heka.DataAccess.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class Incident
    {
        public int Id { get; set; }
        public Nullable<int> MachineId { get; set; }
        public Nullable<int> IncidentCategoryId { get; set; }
        public Nullable<int> IncidentStatus { get; set; }
        public string Description { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> CreatedUserId { get; set; }
        public Nullable<int> StartedUserId { get; set; }
        public Nullable<int> EndUserId { get; set; }
        public Nullable<int> ShiftId { get; set; }
        public Nullable<System.DateTime> ShiftBelongsToDate { get; set; }
    
        public virtual IncidentCategory IncidentCategory { get; set; }
        public virtual Shift Shift { get; set; }
        public virtual Machine Machine { get; set; }
    }
}
