//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heka.DataAccess.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemRequestApproveLog
    {
        public int Id { get; set; }
        public Nullable<int> ItemRequestId { get; set; }
        public Nullable<int> OldRequestStatus { get; set; }
        public Nullable<int> NewRequestStatus { get; set; }
        public Nullable<int> ActorUserId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
    
        public virtual ItemRequest ItemRequest { get; set; }
        public virtual User User { get; set; }
    }
}
