//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heka.DataAccess.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemOrderConsume
    {
        public int Id { get; set; }
        public Nullable<int> ItemOrderDetailId { get; set; }
        public Nullable<int> ConsumerReceiptDetailId { get; set; }
        public Nullable<int> ConsumedReceiptDetailId { get; set; }
        public Nullable<decimal> UsedQuantity { get; set; }
        public Nullable<decimal> UsedGrossQuantity { get; set; }
        public Nullable<int> UnitId { get; set; }
    
        public virtual ItemOrderDetail ItemOrderDetail { get; set; }
        public virtual ItemReceiptDetail ItemReceiptDetail { get; set; }
        public virtual ItemReceiptDetail ItemReceiptDetail1 { get; set; }
        public virtual UnitType UnitType { get; set; }
    }
}
