//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heka.DataAccess.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ItemRequest
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ItemRequest()
        {
            this.ItemOrder = new HashSet<ItemOrder>();
            this.ItemRequestApproveLog = new HashSet<ItemRequestApproveLog>();
            this.ItemRequestDetail = new HashSet<ItemRequestDetail>();
        }
    
        public int Id { get; set; }
        public string RequestNo { get; set; }
        public Nullable<int> RequestType { get; set; }
        public Nullable<System.DateTime> DateOfNeed { get; set; }
        public Nullable<int> RequestStatus { get; set; }
        public Nullable<int> PlantId { get; set; }
        public string Explanation { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUserId { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedUserId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemOrder> ItemOrder { get; set; }
        public virtual Plant Plant { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemRequestApproveLog> ItemRequestApproveLog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ItemRequestDetail> ItemRequestDetail { get; set; }
    }
}
