//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heka.DataAccess.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class LayoutObjectType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public LayoutObjectType()
        {
            this.MachineGroup = new HashSet<MachineGroup>();
        }
    
        public int Id { get; set; }
        public string ObjectTypeCode { get; set; }
        public string ObjectTypeName { get; set; }
        public byte[] ObjectData { get; set; }
        public string DataTypeExtension { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MachineGroup> MachineGroup { get; set; }
    }
}
