//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heka.DataAccess.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachineMaintenanceInstruction
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MachineMaintenanceInstruction()
        {
            this.MachineMaintenanceInstructionEntry = new HashSet<MachineMaintenanceInstructionEntry>();
        }
    
        public int Id { get; set; }
        public Nullable<int> MachineId { get; set; }
        public string UnitName { get; set; }
        public string PeriodType { get; set; }
        public string ToDoList { get; set; }
        public string Responsible { get; set; }
        public Nullable<int> LineNumber { get; set; }
    
        public virtual Machine Machine { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MachineMaintenanceInstructionEntry> MachineMaintenanceInstructionEntry { get; set; }
    }
}
