//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heka.DataAccess.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachinePlan
    {
        public int Id { get; set; }
        public Nullable<int> MachineId { get; set; }
        public Nullable<int> WorkOrderDetailId { get; set; }
        public Nullable<int> OrderNo { get; set; }
    
        public virtual Machine Machine { get; set; }
        public virtual WorkOrderDetail WorkOrderDetail { get; set; }
    }
}
