//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heka.DataAccess.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class MachineMaintenanceInstructionEntry
    {
        public int Id { get; set; }
        public Nullable<int> InstructionId { get; set; }
        public Nullable<int> CreatedUserId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<bool> IsChecked { get; set; }
        public string Explanation { get; set; }
    
        public virtual MachineMaintenanceInstruction MachineMaintenanceInstruction { get; set; }
    }
}
