//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heka.DataAccess.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class MoldTest
    {
        public int Id { get; set; }
        public Nullable<int> MachineId { get; set; }
        public Nullable<System.DateTime> TestDate { get; set; }
        public string ProductDescription { get; set; }
        public Nullable<int> RawMaterialId { get; set; }
        public string RawMaterialName { get; set; }
        public Nullable<decimal> RawMaterialGr { get; set; }
        public string RawMaterialGrText { get; set; }
        public Nullable<int> InflationTimeSeconds { get; set; }
        public Nullable<int> TotalTimeSeconds { get; set; }
        public Nullable<int> DyeId { get; set; }
        public string DyeCode { get; set; }
        public string RalCode { get; set; }
        public string PackageDimension { get; set; }
        public Nullable<int> InPackageQuantity { get; set; }
        public Nullable<int> NutQuantity { get; set; }
        public string NutCaliber { get; set; }
        public Nullable<int> InPalletPackageQuantity { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string ProductCode { get; set; }
        public string ProductName { get; set; }
        public Nullable<int> MoldId { get; set; }
        public string MoldCode { get; set; }
        public string MoldName { get; set; }
        public Nullable<int> PlantId { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUserId { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedUserId { get; set; }
        public Nullable<decimal> RawMaterialTolerationGr { get; set; }
    
        public virtual Machine Machine { get; set; }
        public virtual Mold Mold { get; set; }
        public virtual Dye Dye { get; set; }
    }
}
