//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heka.DataAccess.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductQualityDataDetail
    {
        public int Id { get; set; }
        public Nullable<int> ProductQualityDataId { get; set; }
        public Nullable<int> ProductQualityPlanId { get; set; }
        public Nullable<int> OrderNo { get; set; }
        public Nullable<bool> CheckResult { get; set; }
        public Nullable<decimal> NumericResult { get; set; }
        public Nullable<bool> IsOk { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUserId { get; set; }
    
        public virtual ProductQualityPlan ProductQualityPlan { get; set; }
        public virtual ProductQualityData ProductQualityData { get; set; }
    }
}
