//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heka.DataAccess.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductQualityPlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductQualityPlan()
        {
            this.ProductQualityDataDetail = new HashSet<ProductQualityDataDetail>();
        }
    
        public int Id { get; set; }
        public string ProductQualityCode { get; set; }
        public string CheckProperties { get; set; }
        public string PeriodType { get; set; }
        public string AcceptanceCriteria { get; set; }
        public string ControlDevice { get; set; }
        public string Method { get; set; }
        public string Responsible { get; set; }
        public Nullable<int> OrderNo { get; set; }
        public int CheckType { get; set; }
        public Nullable<decimal> ToleranceMin { get; set; }
        public Nullable<decimal> ToleranceMax { get; set; }
        public string MoldTestFieldName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductQualityDataDetail> ProductQualityDataDetail { get; set; }
    }
}
