//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heka.DataAccess.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class SystemParameter
    {
        public int Id { get; set; }
        public string PrmCode { get; set; }
        public string PrmValue { get; set; }
        public Nullable<int> PlantId { get; set; }
    }
}
