//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heka.DataAccess.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class TransactionLog
    {
        public int Id { get; set; }
        public Nullable<int> TransactionType { get; set; }
        public Nullable<System.DateTime> TransactionDate { get; set; }
        public string Title { get; set; }
        public string Message { get; set; }
        public Nullable<int> UserId { get; set; }
        public Nullable<int> RecordId { get; set; }
        public Nullable<int> ObjectType { get; set; }
    
        public virtual User User { get; set; }
    }
}
