//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Heka.DataAccess.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkOrder()
        {
            this.WorkOrderControl = new HashSet<WorkOrderControl>();
            this.WorkOrderItemNeeds = new HashSet<WorkOrderItemNeeds>();
            this.WorkOrderSerial = new HashSet<WorkOrderSerial>();
            this.WorkOrderDetail = new HashSet<WorkOrderDetail>();
        }
    
        public int Id { get; set; }
        public string WorkOrderNo { get; set; }
        public string DocumentNo { get; set; }
        public Nullable<System.DateTime> WorkOrderDate { get; set; }
        public Nullable<int> FirmId { get; set; }
        public Nullable<int> PlantId { get; set; }
        public Nullable<int> WorkOrderStatus { get; set; }
        public string Explanation { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public Nullable<int> CreatedUserId { get; set; }
        public Nullable<System.DateTime> UpdatedDate { get; set; }
        public Nullable<int> UpdatedUserId { get; set; }
        public Nullable<int> WorkOrderType { get; set; }
        public string TrialFirmName { get; set; }
        public Nullable<int> WorkOrderCategoryId { get; set; }
    
        public virtual Firm Firm { get; set; }
        public virtual Plant Plant { get; set; }
        public virtual WorkOrderCategory WorkOrderCategory { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkOrderControl> WorkOrderControl { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkOrderItemNeeds> WorkOrderItemNeeds { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkOrderSerial> WorkOrderSerial { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkOrderDetail> WorkOrderDetail { get; set; }
    }
}
